config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'

  devise_for :users
 
  root "pages#main"


  
  resources :users do
    resources :posts, except: :show
  end
  
  resources :posts, only: [:show] do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :views, presence: true



  def increment_view
   self.increment!(:views)
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        
  has_many :posts

  validates :user_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @new_comment = @post.comments.new(comment_params)

    if @new_comment.save
      flash[:notice] = "Comment saved, thank you!"
    else
      flash[:alert] = "Something went wrong"
    end

    redirect_to :root
  end
  


  private

  def comment_params
    params.require(:comment).permit(:guest_name, :body)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  
  def main
    @latest_5_posts = Post.order(created_at: :desc).limit(5)
   
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def new
    @user = current_user
    @new_post = current_user.posts.new
          
  end

  
  def create
    @user = current_user
    @new_post = current_user.posts.new(post_params)
 
    if @new_post.save
      redirect_to :root, notice: "Post created succesfully"
      
    else
      
      flash.now[:alert] = "Something went wrong"
      render :new,  status: :unprocessable_entity 
    end

  end


  def show
    @post = Post.find(params[:id])
    # We increment the counter
    @post.increment_view

        @new_comment = @post.comments.new
    

    
  end
   
  def index
    @last_10_posts = current_user.posts.order(created_at: :desc).limit(10)

  end

  def edit
    @user = current_user
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
   
    if @post.update(post_params)
      flash[:notice] = "The post was updated succesfully"
    else
      flash[:alert] = "Something went wrong. We couldnt update the post"
    end
    redirect_to user_posts_path(current_user.id)
  end


  def destroy
    @post = Post.find(params[:id])
   
    ActiveRecord::Base.transaction do
      @post.comments.destroy_all
      @post.destroy
      redirect_to user_posts_path(current_user.id)
    end
    
  end


  private

  def post_params
    params.require(:post).permit(:title, :body)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TennisBlog</title>
    <link rel="icon" href="<%= asset_path('hypnotize.svg') %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav> <%= render partial: "shared/navbar"%></nav>
    <%= render partial: "shared/flash_messages" %>
    <main><%= yield %></main>
    <footer>  <%= render partial: "shared/footer"%>  </footer>
  </body>
</html>

app/views/pages/main.html.erb
<div class="container-fluid w-50 mt-5">

    <h1 class= "text-center mb-5">Welcome to Tennis Tribune</h1>
   
    
    <div class="container custom-main-cards-container">
        <% @latest_5_posts.each do |post|%>
            <%= render partial: "shared/post-preview", locals: {post: post} %> <br>
        <% end %>
    </div>


</div>

app/views/posts/_comment-form.html.erb
<%= form_with model:[post, new_comment] do |form|%>

    <div class="form-comments-main">
        <div class="form-comments-main-name">
            <%= form.text_field :guest_name, placeholder: "Enter your name"%>
        </div>
        <div class="form-comments-main-body">
            <%= form.text_area :body, placeholder: "Write your comment"%>
        </div>
    </div>

    <div class="form-comments-actions">
        <%= form.submit "Submit", class: "form-comments-actions-button"%>
    </div>

<% end %>

app/views/posts/_comments.html.erb
<% comments.each do |comment|%>

    <div class="card-comment mb-3">

        <div class="card-comment-name">
            <%= comment.guest_name %>
        </div>
        <div class="card-comment-info"> 
            <% if comment.persisted? %>
                <%= time_ago_in_words(comment.created_at) %> ago
            <% end %>
        </div>
        <div class="card-comment-body">
            <%= comment.body %>
        </div>

    </div>

<% end %>

app/views/posts/_user-post-list.html.erb
<% posts.each do |post|%>

    <div class= "custom-card-index">

        <div class="custom-card-index__left">
            <div class="custom-card-main__title--small ">
                <%= link_to post.title, post_path(post.id)%>
            </div>
            <div class="custom-card-main__stats">
                <div class= "custom-card-main__stats__item"> <%= post.created_at.strftime('%Y-%m-%d') %>
            </div>
                <div class= "custom-card-main__stats__item"> <%= post.views%> views </div>
            </div>
        </div>
       
       <div class="custom-card-index__right">
        <div class="custom-card-index__actions">
            <%= link_to edit_user_post_path(current_user.id, post.id) do %>
                <%= image_tag("edit_pencil.svg") %>
            <% end %>
        
            <%= link_to user_post_path(current_user.id, post.id), 
                data: {turbo_method: :delete, confirm: "Are you sure you want to delete this post?" } do %>
                <%= image_tag("delete_trash.svg") %>
            <% end %>
        </div>
       </div>

     </div>


<% end %>

app/views/posts/edit.html.erb
<div class="container-fluid w-75">
    <div class="custom-new-post-form">
        <div class="custom-new-post-form__header">
            <h1>Edit your post</h1>
        </div>
    
    
        <%= form_with model: [@user, @post] do |form|%>
    
            <div class="row custom-new-post-form__title">
                <div class="custom-post__label"><%= form.label :title, "Title" %></div>
                <%= form.text_field :title %>
            </div>
    
            <div class="row custom-new-post-form__body">
                <div class="custom-post__label"><%= form.label :body, "Post Content" %></div>
                <%= form.text_area :body %>
            </div>

            <div class="row custom-new-post-form__actions">
                <%= form.submit "Submit Post" %>
            </div>
    
        <% end%>
    
    
    </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid w-50 mt-5 ">

     <div class="row mb-5">
         <div class="col text-center">
            <h1>All your Posts</h1>
         </div>
     </div>

    <div class="row">
        <div class="col">
            <%= render partial: "user-post-list",
            locals:{posts: @last_10_posts}%>
        </div>
    </div>
    
    
</div>

app/views/posts/new.html.erb
<div class="container-fluid w-75">
    <div class="custom-new-post-form">
        <div class="custom-new-post-form__header">
            <h1>Create a new post</h1>
        </div>
    
    
        <%= form_with model: [@user, @new_post] do |form|%>
    
            <div class="row custom-new-post-form__title mb-3">
                
                <%= form.text_field :title, placeholder: "Post Title" %>
            </div>
    
            <div class="row custom-new-post-form__body">
                
                <%= form.text_area :body, placeholder: "Write your Post" %>
            </div>

            <div class="row custom-new-post-form__actions mt-3">
                <%= form.submit "Submit Post" %>
            </div>
    
        <% end%>
    
    
    </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid ">
    <div class="container-fluid w-50">
        <div class="row">
            <div class="col">
                <h1><%= @post.title%></h1>
            </div>
    
        </div>
    
        <div class="row">
            <div class="col">
               <%= simple_format(@post.body) %>
            </div>
    
        </div>

        <div class="row">
            <div class="col custom-comments-counter">
            <% if @post.comments.count > 0%>
                <%= @post.comments.count%> Comments
            <% else %>
                No comments yet. Leave us yours!

            <% end %>
            
            </div>
        
        </div>
    
    
            
        <div class="row">
                <div class="col custom-form-comments">
                    <%= render partial: "comment-form",
                    locals: {post: @post, new_comment: @new_comment} %>
                </div>
        </div>


        <div class="row">
            <div class="col custom-comments">
                <%= render partial: "comments",
                locals: {comments: @post.comments}%>
            </div>

        </div>

    </div>


</div>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
   <div class="container-fluid d-flex justify-content-center">
   
    <span class="navbar-brand mb-0 h1">The Odin Project</span>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TTribune</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if current_user%>
            <div class="dropdown">
              <a class="btn btn-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Posts
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Post", new_user_post_path(current_user), class: "nav-link"%></li>
                <li><%= link_to "Your Posts", user_posts_path(current_user), class: "nav-link"%></li>
              </ul>
            </div>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">

        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-light mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_post-preview.html.erb
<div class= "custom-card-main ">

    <div class="custom-card-main__title"> 
        <%= link_to post.title, post_path(post.id)%>
    </div>

    <div class="custom-card-main__stats">
        <div class= "custom-card-main__stats__item"> 
            <%= post.created_at.strftime('%Y-%m-%d') %>
        </div>
        <div class= "custom-card-main__stats__item"> 
            <%= post.views%> views 
        </div>          
        <% if user_signed_in? %>
            <div class= "custom-card-main__stats__item"> 
                author: <%= post.user.user_name%>  
            </div>        
        <% end %>


    </div>

    <div class="custom-card-main__body"> 
        <%= truncate(post.body, length: 400) %>
    </div>

</div>